## Cat task - Yandex Coursera 

Import file with text

In [1]:
import re
from scipy import spatial
import numpy as np

In [2]:
with open('./sentences.txt', 'r') as file:
    local_file = list(file)
    file.readlines()
    file.close()

In [3]:
temp_list=[]

#Приводим весть текст к нижнему регистру 

for line in local_file:
    #Приводим весть текст к нижнему регистру 
    exp_line = line.lower()
    #Убираем пробели, знаки, оставляем только слова 
    str_list = list(filter(None, (re.split('[^a-z]', exp_line))))
    temp_list.append(str_list)
    #print(temp_list)

In [4]:
for line in temp_list:
    print(line, end='')

['in', 'comparison', 'to', 'dogs', 'cats', 'have', 'not', 'undergone', 'major', 'changes', 'during', 'the', 'domestication', 'process']['as', 'cat', 'simply', 'catenates', 'streams', 'of', 'bytes', 'it', 'can', 'be', 'also', 'used', 'to', 'concatenate', 'binary', 'files', 'where', 'it', 'will', 'just', 'concatenate', 'sequence', 'of', 'bytes']['a', 'common', 'interactive', 'use', 'of', 'cat', 'for', 'a', 'single', 'file', 'is', 'to', 'output', 'the', 'content', 'of', 'a', 'file', 'to', 'standard', 'output']['cats', 'can', 'hear', 'sounds', 'too', 'faint', 'or', 'too', 'high', 'in', 'frequency', 'for', 'human', 'ears', 'such', 'as', 'those', 'made', 'by', 'mice', 'and', 'other', 'small', 'animals']['in', 'one', 'people', 'deliberately', 'tamed', 'cats', 'in', 'a', 'process', 'of', 'artificial', 'selection', 'as', 'they', 'were', 'useful', 'predators', 'of', 'vermin']['the', 'domesticated', 'cat', 'and', 'its', 'closest', 'wild', 'ancestor', 'are', 'both', 'diploid', 'organisms', 'that',

In [6]:

# собираем всем уникальные слова всего текста в один set()

output = set()
for line in temp_list:
    for j in line:
        output.add(j)
#print(sorted(output))

# Всего должны получить 254 уникальных слова

print(len(output))


254


Словарь вхождения слов 

In [7]:
list_of_words = list(output)
list_of_order_values = list(range(254))
dict_of_words = dict(zip(output, list_of_order_values))


Создаем матрицу `n*d` где n число строк, a d число всех слов

In [71]:
# Создаем пустую матрицу нулей размером 22 на 254
cat_matrix = np.zeros([22,254])
position_line = 0

# Пока счеткик меньше кол-ва предложений бежим по линиями в листе
while position_line < len(temp_list):
    for line in temp_list:
        # Генерим пустой лист для каждой линии
        chisla_for_matrix = []
        for word in line:
            #print(word, end=' ')
            #print(dict_of_words[word])
            
            #В пустой лист добавляет номера слов которые встречаются в предложении путем получения их через ключ
            
            chisla_for_matrix.append(dict_of_words[word]) 

        # В этом цикле мы увеличиваем на 1 значение (i,j) в матрице есть слово есть в предложение
        for position_number in chisla_for_matrix:
            #print(position_line, position_number)
            cat_matrix[position_line, position_number] += 1
        #print('\n')
        
        #Бежим на новую строчку
        
        position_line +=1


In [66]:
cat_matrix.max(1)

array([1., 2., 3., 2., 2., 2., 2., 2., 2., 3., 2., 2., 2., 1., 2., 2., 2.,
       2., 1., 2., 1., 1.])

Находим `scipy.spatial.distance.cosine` для всех первого предложения

In [32]:
from scipy import spatial

In [33]:
cat_matrix[0,:].shape

(254,)

In [34]:
scipy.spatial.distance.cosine(cat_matrix[0,:], cat_matrix[1,:])

0.9527544408738466

In [41]:
cat_matrix[:,0]

array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.])

In [107]:
cosine_list = []
str_list=[]
for lines in range(len(cat_matrix)):
    #print(lines)
    result = scipy.spatial.distance.cosine(cat_matrix[0,:], cat_matrix[lines,:])
    #print(result)
    cosine_list.append(result)
    str_list.append(str(np.around(result, 3)))

In [74]:
cosine_matrix = np.array(cosine_list)

In [80]:
list_of_answers = list(np.around(cosine_matrix, 3))

In [110]:
dict_of_answers = dict(zip(str_list, range(len(list_of_answers))))

In [113]:
dict_of_answers['0.953']

1

In [77]:
round_cosine = np.around(cosine_matrix, 3)

In [78]:
np.sort(np.around(cosine_matrix,3))

array([0.   , 0.733, 0.777, 0.825, 0.833, 0.84 , 0.841, 0.843, 0.864,
       0.87 , 0.874, 0.88 , 0.884, 0.889, 0.895, 0.906, 0.926, 0.94 ,
       0.944, 0.944, 0.953, 0.957])

In [26]:
round_cosine.argmax(axis=0)
indices = np.where(round_cosine == round_cosine.max())

In [27]:
indices

(array([17]),)

## Results

In [28]:
print('Два наиболее схожих предлложения имеют номера 1 and 17 и значения:', round_cosine[1],round_cosine[17])

Два наиболее схожих предлложения имеют номера 1 and 17 и значения: 0.953 0.957


In [119]:
!echo "6 4" > result_cats.txt

In [118]:
answer_1 = dict_of_answers['0.733'] 
answer_2 = dict_of_answers['0.777']
print(f'Два наиболее схожих предлложения имеют номера {answer_1} and {answer_2} и значения:')

Два наиболее схожих предлложения имеют номера 6 and 4 и значения:
