## Optimiztion 

In [43]:
np.log10(1)

0.0

In [1]:
import numpy as np 
import scipy

from scipy.optimize import minimize

In [19]:
from sklearn import linear_model

In [36]:
SGD_model = linear_model.SGDRegressor(alpha=0, tol=1e-8, max_iter=1e4)
lin_model = linear_model.LinearRegression()

In [37]:
from sklearn import datasets

In [38]:
df = datasets.make_regression(n_samples=100, n_features=2, n_targets=1)

In [39]:
df

(array([[ 0.06147844, -0.44732063],
        [-2.03915648, -0.56615639],
        [-1.56968678,  1.17344844],
        [-0.75053653, -0.21474917],
        [ 0.6335806 ,  0.38989556],
        [-0.66646514,  0.1736676 ],
        [ 0.34973808,  0.11181399],
        [ 0.16864519, -0.47170607],
        [ 0.43238127,  0.50127507],
        [ 0.54771321,  0.6085688 ],
        [-0.2614788 ,  0.02117797],
        [-0.3052414 , -0.81247591],
        [ 0.15682791, -0.28256325],
        [ 0.21853157,  0.91995642],
        [ 0.55206907,  1.33981925],
        [ 1.99746806,  0.23000363],
        [-0.18624119,  1.26467787],
        [ 0.12475151,  0.82123353],
        [-0.88411451, -0.23256438],
        [ 0.46581662, -1.03405548],
        [-0.90708594,  1.38442261],
        [-0.80896075, -1.61510199],
        [-0.152227  , -3.23622023],
        [ 2.22458439,  0.13123347],
        [-0.74264903,  1.71733749],
        [ 0.70742777, -1.13736043],
        [ 0.40068432, -0.59034998],
        [-0.64375515, -0.132

In [40]:
SGD_model.fit(df[0], df[1])
lin_model.fit(df[0], df[1])


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [41]:
SGD_model.coef_

array([34.82622157, 90.54046169])

In [42]:
lin_model.coef_

array([34.82615494, 90.5406431 ])

In [46]:
def f(x):
    return np.sin(x / 5.) * np.exp(x / 10.) + 5. * np.exp(-x / 2.)

In [4]:
from scipy import optimize

`BFGS` module

In [42]:
res_2 = minimize(f, 2, method='BFGS', options={'disp':True})
res_30 = minimize(f, 30, method='BFGS', options={'disp':True})

Optimization terminated successfully.
         Current function value: 1.745268
         Iterations: 6
         Function evaluations: 21
         Gradient evaluations: 7
Optimization terminated successfully.
         Current function value: -11.898895
         Iterations: 6
         Function evaluations: 21
         Gradient evaluations: 7


In [38]:
res_2.x

array([4.13627619])

In [40]:
float(res_2.x)

4.136276187631968

In [65]:
answers = []
answers.append(f(float(res_2.x)))
answers.append(f(float(res_30.x)))

In [62]:
answers

[1.745268290344928, -11.898894665981322]

## `scipy.optimize.differential_evolution.`

In [44]:
from scipy.optimize import differential_evolution

In [45]:
bounds = [2,30], [2,30]

dif_evol = differential_evolution(f, [[1,30]])

NameError: name 'f' is not defined

In [59]:
f(dif_evol.x)

array([-11.89889467])

In [66]:
answers.append(float(f(dif_evol.x)))

In [67]:
answers

[1.745268290344928, -11.898894665981322, -11.898894665981146]

## Оптимизация негладкой функции 

In [69]:
#определим ступенчатую функцию
def h(x):
    return int(f(x))

In [70]:
res_h_2 = minimize(h, 2, method='BFGS', options={'disp':True})
res_h_30 = minimize(h, 30, method='BFGS', options={'disp':True})

Optimization terminated successfully.
         Current function value: 2.000000
         Iterations: 0
         Function evaluations: 3
         Gradient evaluations: 1
Optimization terminated successfully.
         Current function value: -5.000000
         Iterations: 0
         Function evaluations: 3
         Gradient evaluations: 1


In [72]:
res_h_30.x

array([30.])

In [73]:
h(30)

-5

In [74]:
answers.append(h(30))

In [75]:
answers

[1.745268290344928, -11.898894665981322, -11.898894665981146, -5]

In [78]:
dif_evol = differential_evolution(h, [[1,30]])
print(dif_evol.x)

answers.append(h(dif_evol.x))

[26.96392747]


In [79]:
answers

[1.745268290344928, -11.898894665981322, -11.898894665981146, -5, -11]

In [90]:
tf = open('optimiztion_w3_1.txt', 'w')
for x in answers[:2]:
   tf.write(str(x)+' ')
tf.close()

#tf = open('optimiztion_w3_2.txt', 'w')
#for x in answers[2]:
#   tf.write(str(x)+' ')
#tf.close()

tf = open('optimiztion_w3_3.txt', 'w')
for x in answers[3:]:
   tf.write(str(x)+' ')
tf.close()

In [88]:
answers[2]

-11.898894665981146

In [91]:
!echo "-11.898894665981146" > optimiztion_w3_2.txt


In [94]:
!cat optimiztion_w3_3.txt

-5 -11 

## Rosenbrock function

In [13]:
import numpy as np

def rosen(x):
    """The Rosenbrock function"""
    return np.sum(100.0*(x[1:]-x[:-1]**2.0)**2.0 + (1-x[:-1])**2.0, axis=0)

In [18]:
rosen(x0)

848.22

In [14]:
from scipy.optimize import minimize
x0 = np.array([1.3, 0.7, 0.8, 1.9, 1.2])
res = minimize(rosen, x0, method='nelder-mead',
    options={'xtol': 1e-8, 'disp': True})
print(res.x)

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 339
         Function evaluations: 571
[1. 1. 1. 1. 1.]


In [107]:
a = np.array([8, 10, -1, 0, 0])

In [108]:
a.shape

(5,)

In [97]:
a.reshape(5,1).shape

(5, 1)

In [109]:
a = a[:, np.newaxis]

In [110]:
a.shape

(5, 1)

SVD

In [113]:
np.set_printoptions(precision=2, suppress=True)

In [114]:
X = np.array([[1,2,0],
              [0,0,5],
              [3,-4,2],
              [1,6,5],
              [0,1,0]])

In [115]:
np.linalg.svd(X)

(array([[ 0.17,  0.16, -0.53, -0.8 , -0.16],
        [ 0.39, -0.53,  0.61, -0.43,  0.03],
        [-0.14, -0.82, -0.52,  0.14,  0.07],
        [ 0.89,  0.06, -0.25,  0.38, -0.06],
        [ 0.08,  0.11, -0.08, -0.11,  0.98]]),
 array([8.82, 6.14, 2.53]),
 array([[ 0.07,  0.72,  0.69],
        [-0.37,  0.67, -0.65],
        [-0.93, -0.21,  0.31]]))

In [116]:
U, s, W = np.linalg.svd(X)

In [118]:
U.T

array([[ 0.17,  0.39, -0.14,  0.89,  0.08],
       [ 0.16, -0.53, -0.82,  0.06,  0.11],
       [-0.53,  0.61, -0.52, -0.25, -0.08],
       [-0.8 , -0.43,  0.14,  0.38, -0.11],
       [-0.16,  0.03,  0.07, -0.06,  0.98]])

In [121]:
D = np.zeros_like(X)

In [127]:
d = D[np.diag_indices(min(X.shape))]

In [128]:
d

array([0, 0, 0])